
---CRIE AS TABELAS E O INDICES PARA O MODELO DE DADOS A SEGUIR, INCLUINDO OS RELACIONAMENTOS 
---E OS RELACIONAMENTOS E TODA A INTEGRIDADE REFENRENCIAL:

CREATE TABLE BAIRRO (
	CDBAIRRO INTEGER NOT NULL,
	NMBAIRRO VARCHAR(20) NULL,
	CDCIDADE INTEGER NOT NULL,
	SGESTADO CHAR(2) NOT NULL
);

CREATE INDEX XIF8BAIRRO ON BAIRRO (
	CDCIDADE ASC,
	SGESTADO ASC
);

ALTER TABLE BAIRRO
	ADD CONSTRAINT XPKBAIRRO PRIMARY KEY (CDBAIRRO, CDCIDADE, SGESTADO
);

CREATE TABLE CIDADE (
	CDCIDADE INTEGER NOT NULL,
	NMCIDADE VARCHAR(20) NULL,
	SGESTADO CHAR(2) NOT NULL,
);

CREATE INDEX XIF7CIDADE ON CIDADE (
	SGESTADO ASC
);

ALTER TABLE CIDADE
	ADD CONSTRAINT XPKCIDADE PRIMARY KEY (CDCIDADE, SGESTADO
);

CREATE TABLE COMPRADOR (
	CDCOMPRADOR INTEGER NOT NULL,
	NMCOMPRADOR VARCHAR(40) NULL,
	NMENDERECO VARCHAR(40) NULL,
	NRCPF DECIMAL(11) NULL,
	NMCIDADE VARCHAR(20)NULL,
	NMBAIRRO VARCHAR (20) NULL,
	SGESTADO CHAR(2) NULL,
	TELEFONE VARCHAR(20) NULL,
	EMAIL VARCHAR(80) NULL
);

ALTER TABLE COMPRADOR
	ADD CONSTRAINT XPKCOMPRADOR PRIMARY KEY (CDCOMPRADOR
);

CREATE TABLE ESTADO (
	SGESTADO CHAR(2) NOT NULL,
	NMESTADO VARCHAR(20) NULL
);

ALTER TABLE ESTADO 
	ADD CONSTRAINT XPKESTADO PRIMARY KEY (SGESTADO
);

CREATE TABLE FAIXA_IMOVEL (
	CDFAIXA INTEGER NOT NULL,
	NMFAIXA VARCHAR(30) NULL,
	VLMINIMO DECIMAL(14,2) NULL,
	VLMAXIMO DECIMAL(14,2) NULL
);

ALTER TABLE FAIXA_IMOVEL
	ADD CONSTRAINT XPKFAIXA_IMOVEL PRIMARY KEY (CDFAIXA
);

CREATE TABLE IMOVEL (
	CDIMOVEL INTEGER NOT NULL,
	CDVENDEDOR INTEGER NULL,
	CDBAIRRO INTEGER NULL,
	CDCIDADE INTEGER NULL,
	SGESTADO CHAR(2) NULL,
	NMENDEREÇO VARCHAR(40) NULL,
	NRAREAUTIL DECIMAL(10,2) NULL,
	NRAREATOTAL DECIMAL(10,2) NULL,
	DSIMOVEL VARCHAR(300) NULL,
	VLPRECO DECIMAL(16,2)NULL,
	NROFERTAS INTEGER NULL,
	STVENDIDO CHAR(1) NULL,
	DTLANCTO DATE NULL,
	IMOVEL_INDICADO INTEGER NULL
);

CREATE INDEX XIF12IMOVEL ON IMOVEL (CDVENDEDOR ASC
);

CREATE INDEX XIF13IMOVEL ON IMOVEL ( IMOVEL_INDICADO ASC
);

CREATE INDEX XIF9IMOVEL ON IMOVEL (
	CDBAIRRO ASC,
	CDCIDADE ASC,
	SGESTADO ASC
);

ALTER TABLE IMOVEL 
	ADD CONSTRAINT XPKIMOVEL PRIMARY KEY (CDIMOVEL
);

CREATE TABLE OFERTA (
	CDCOMPRADOR DECIMAL(16,2) NOT NULL,
	CDIMOVEL INTEGER NOT NULL,
	VLOFERTA NUMERIC(16,2) NULL,
	DTOFERTA DATE NULL
);

CREATE INDEX XIF10OFERTA ON OFERTA ( CDCOMPRADOR ASC );

CREATE INDEX XIF11OFERTA ON OFERTA ( CDIMOVEL ASC );

ALTER TABLE OFERTA
	ADD CONSTRAINT XPKOFERTA PRIMARY KEY (CDCOMPRADOR,
	CDIMOVEL
);

CREATE TABLE VENDEDOR (
	CDVENDEDOR INTEGER NOT NULL,
	NMVENDEDOR VARCHAR(40) NULL,
	NMENDERECO VARCHAR(40)NULL,
	NRCPF DECIMAL(11)NULL,
	NMCIDADE VARCHAR(20) NULL,
	NMBAIRRO VARCHAR(20) NULL,
	SGESTADO CHAR(2) NULL,
	TELEFONE VARCHAR(20) NULL,
	EMAIL VARCHAR(80) NULL
);

ALTER TABLE VENDEDOR
	ADD CONSTRAINT XPKVENDEDOR PRIMARY KEY (CDVENDEDOR
);

ALTER TABLE BAIRRO
	ADD CONSTRAINT CIDADE_BAIRRO
	FOREIGN KEY ( CDCIDADE, SGESTADO )
	REFERENCES CIDADE

ALTER TABLE CIDADE
	ADD CONSTRAINT ESTADO_CIDADE
	FOREIGN KEY ( SGESTADO )
	REFERENCES ESTADO

ALTER TABLE IMOVEL
	ADD CONSTRAINT IMOVEL_INDICADO
	FOREIGN KEY ( IMOVEL_INDICADO )
	REFERENCES IMOVEL

ALTER TABLE IMOVEL
	ADD CONSTRAINT VENDEDOR_IMOVEL
	FOREIGN KEY ( CDVENDEDOR )
	REFERENCES VENDEDOR

ALTER TABLE IMOVEL
	ADD CONSTRAINT BAIRRO_IMOVEL
	FOREIGN KEY ( CDBAIRRO, CDCIDADE, SGESTADO )
	REFERENCES BAIRRO

ALTER TABLE OFERTA
	ADD CONSTRAINT IMOVEL_OFERTA
	FOREIGN KEY ( CDIMOVEL )
	REFERENCES IMOVEL

ALTER TABLE OFERTA
	ADD  CONSTRAINT COMPRADOR_OFERTA
	FOREIGN KEY ( CDCOMPRADOR )
	REFERENCES COMPRADOR


